Microsite
saasquatch/schema pull request #65
Opened 2022-06-01 16:58 UTC by slisaasquatch

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

- Jira issue number: (PUT IT HERE)
- Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run (if applicable)
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist

### Code review

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2022-06-21 18:32 UTC, johanventer submitted a review, later dismissed

2022-07-05 16:22 UTC, ianhitchcock requested changes
Aside from updating the release version, looks good to me 👍

2022-07-05 22:38 UTC, johanventer requested changes

2022-07-05 22:38 UTC, johanventer commented on src/json/microsite/MicrositePageConfigValues.schema.json
> +    }
Delete, we don't have a good way of swapping it out.

2022-07-21 17:01 UTC, johanventer approved these changes

2022-07-21 17:02 UTC, merged